# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: FreedomofthePressFoundation.Dangerzone
PackageVersion: 0.5.1
PackageLocale: en-US
Publisher: Freedom of the Press Foundation
PackageName: Dangerzone
License: AGPL-3.0
ShortDescription: Take potentially dangerous PDFs, office documents, or images and convert them to safe PDFs
ManifestType: defaultLocale
ManifestVersion: 1.5.0
